---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM resources for watch editorials stack'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'Stack Parameters'
        Parameters:
          - Environment
Parameters:
  Environment:
    Description: 'Environment'
    Type: String
    AllowedValues: ['dev', 'qa', 'prod']
Resources:
  Policy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 's3:GetBucketLocation'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
            Resource:
              - !Sub 'arn:aws:s3:::${Environment}-editorials-watch-aetnd-com'
          - Effect: 'Allow'
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:DeleteObject'
              - 's3:GetObject'
              - 's3:ListMultipartUploadParts'
              - 's3:PutObject'
            Resource:
              - !Sub 'arn:aws:s3:::${Environment}-editorials-watch-aetnd-com/*'
          - Effect: 'Allow'
            Action:
              - 'secretsmanager:GetRandomPassword'
              - 'secretsmanager:ListSecrets'
            Resource: '*'
          - Effect: 'Allow'
            Action:
              - 'secretsmanager:DeleteSecret'
              - 'secretsmanager:DescribeSecret'
              - 'secretsmanager:GetSecretValue'
              - 'secretsmanager:ListSecretVersionIds'
              - 'secretsmanager:PutSecretValue'
              - 'secretsmanager:RestoreSecret'
              - 'secretsmanager:UpdateSecret'
            Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${Environment}/aetn.watch.editorials/*'
          - Effect: 'Allow'
            Action:
              - 'kms:Decrypt'
              - 'kms:DescribeKey'
              - 'kms:GenerateDataKey'
            Resource: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/${Environment}-devops-sops-kms'
Outputs:
  TemplateID:
    Description: 'Template Id.'
    Value: 'base/iam-watch-editorials.yaml'
  TemplateVersion:
    Description: 'Template Version.'
    Value: '__VERSION__'
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  PolicyArn:
    Value: !Ref Policy
    Description: 'Policy Arn'
    Export:
      Name: !Sub '${AWS::StackName}-PolicyArn'
